#!/usr/bin/env zsh

# Get the name of the current branch in this GIT repo

BUILD_SCRIPTS_DIR=$(dirname "$(readlink -f "$0")")
source "${BUILD_SCRIPTS_DIR}/../git/utils"


git symbolic-ref --short HEAD