#!/usr/bin/env zsh

BUILD_SCRIPTS_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck source=../common/utils
source "${BUILD_SCRIPTS_DIR}/../common/utils"

error=$(git status 2>&1 | grep "fatal: not a git repository")
[ -z "$error" ] || fail "This isn't a GIT repository"

maybe_main=$(git branch --list | grep main)
if [ -z "${maybe_main}" ]; then
    export main="master"
else
    export main="main"
fi

rebase_if_remote() {
    remote=$(remote-branch-name)

    if [[ -n "${remote}" ]]; then
        log "Rebasing from remote (${remote})..."
        git pull -r || exit 1
    fi
}

push_changes() {
    push_options=$*
    remote=$(remote-branch-name)

    log "Pushing changes..."
    if [[ -z "${remote}" ]]; then
        git push --set-upstream origin "$(branch-name)" || exit 1
    else
        # shellcheck disable=SC2086
        git push ${push_options} || exit 1
    fi
}
