#!/usr/bin/env zsh

# This utility updates jenv file with the available Java installations assuming:
#   - the different available Java kits are all OpenJDK
#   - the different available Java kits are all installed using Homebrew

while IFS= read -r -d '' jdk; do
  existing_versions=$(jenv add $jdk | grep "already present" | cut -f2 -d\  | tr '\n' ' ')
  for existing_version in ${(z)existing_versions}; do
    echo "Removing $existing_version"
    jenv remove $existing_version
  done
  echo "Adding $jdk"
  jenv add $jdk
done < <(find /opt/homebrew/Cellar -path "*openjdk*" -maxdepth 2 -mindepth 2 -type d -print0)

